# This rule is used for the http -> https redirection
http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https-ratelimit
      rule: "HostRegexp(`{any:.+}`)"
      service: noop

  services:
    # noop service, the URL will be never called
    noop:
      loadBalancer:
        servers:
          # this url is obviously fake
          - url: http://192.168.0.1:1337

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true
    # if you don't want a rate limit, remove te section below
    ratelimit:
      rateLimit:
        average: 40
        burst: 60
    https-ratelimit:
      chain:
        middlewares:
         - https_redirect 
         - ratelimit
